### ISSUE TITLE
`type Content` vs `newtype Content` in chapter 14

### ISSUE THREAD

**Issue by zudov** [paf31/purescript-book-sources#19]
There is a small inconsistency in code sniplets, first we declare

```haskell
type Content = Free ContentF
```

and mention that `newtype` might be used.

Further `Content` is used as if it was declared with a `newtype`:

```haskell
text :: String -> Content Unit
text s = Content $ liftF $ TextContent s unit
```
```haskell
renderContent (Just (Content content)) = do
```

But then it's used as if it was a type synonym for `Free`:

```haskell
renderContentItem :: ContentF (Content Unit) -> Writer String (Content Unit)
```

Perhaps it's better to use type synonym everywhere, `text` and `element` become slightly less readable, but the whole thing becomes consistent and corresponds to the sources in `purescript-book` repo.

**Comment by paf31** [comment]
Thanks, I'll fix this :+1:
