### ISSUE TITLE
Nullary Type Classes v.s. orphan instance

### ISSUE THREAD

**Issue by shybyte** [paf31/purescript-book-sources#20]
For me it seems that the section "Nullary Type Classes" in https://github.com/paf31/purescript-book-sources/blob/master/chapter6.md#nullary-type-classes  does not work with the new orphan instance detection of the compiler. At least I was not able to figure out how to use Nullary Type Classes in the useful way described in this section.

**Comment by paf31** [comment]
Yes, I need to revise that. They are still useful, but not in the same way that is described in the book.

Thanks.
