### ISSUE TITLE
Functor definition by monad in chapter 8 seems to be wrong

### ISSUE THREAD

**Issue by shybyte** [paf31/purescript-book-sources#22]
Exercise 6 in
https://github.com/paf31/purescript-book-sources/blob/master/chapter8.md#monads-and-applicatives
claims that every monad has a default Functor instance given by:
```purescript
 map f a = do
   x <- a
   return (f a)
```

I think that the correct code is

```purescript
 map f a = do
   x <- a
   return (f x)
```

because the following code typechecks and looks for me like the functor signature:

```purescript
map2 :: forall m a b. (Monad m) => (a -> b) -> m a -> m b
map2 f ma = do
  a <- ma
  return (f a)
```

Additionally the type singature 
```purescript
lift2 :: forall f a b c. (Applicative f). (a -> b -> c) -> f a -> f b -> f c
```
should be probably:
```purescript
lift2 :: forall f a b c. (Applicative f) => (a -> b -> c) -> f a -> f b -> f c
```

**Comment by paf31** [comment]
:+1: Thanks for spotting this.
