### ISSUE TITLE
Incorrect catchException example

### ISSUE THREAD

**Issue by shybyte** [paf31/purescript-book-sources#23]
The section https://github.com/paf31/purescript-book-sources/blob/master/chapter8.md#handlers-and-actions contains the following example for catchException

```purescript
main = do
  config <- catchException printException readConfig
  runApplication config
  
  where
  printException e = trace (message e)
```

For me this seems to make no sense because it does not explain what should happen in the error case. Where is the config coming from?

So I guess the code must provide a default value:
```purescript
main = do
  config <- catchException printExceptionReturnDefault readConfig
  runApplication config
  
  where
  printExceptionReturnDefault e = trace (message e) (\_ -> return defaultConfig)
```

**Comment by paf31** [comment]
Thanks for spotting this.
