### ISSUE TITLE
Chapter 6 - What is "id"?

### ISSUE THREAD

**Issue by bkaestner** [paf31/purescript-book-sources#24]
Chapter 6 introduces the Functor laws:

> Type class instances for `Functor` are expected to adhere to a set of laws, called the _functor laws_:
> - `id <$> xs = xs`
> - `g <$> (f <$> xs) = (g <<< f) <$> xs`

But what's `id`? The function is explained in chapter 10, section "Representing Quantified Types":

> Expressions with quantified (polymorphic) types have restrictive representations at runtime. In practice, this means that there are relatively few expressions with a given quantified type, but that we can reason about them quite effectively.
> 
> Consider this polymorphic type, for example:
> 
> ```
> forall a. a -> a
> ```
> 
> What sort of functions have this type? Well, there is certainly one function with this type - namely, the identity function `id`, defined in the `Prelude`:
> 
> ```
> id :: forall a. a -> a
> id a = a
> ```
> 
> In fact, the id function is the only (total) function with this type! 

So `id` isn't really known during the definitions of the laws. I would even go a step further and introduce `id` and the "magic" behind `forall a. a -> a` in chapter 3, section "Quantified Types" instead of `flip` (see #25), to show that quantified types give us something to reason about.

**Comment by paf31** [comment]
Thanks for writing these up. Originally, I planned to leave these out of the text in the early chapters, hoping that the reader would spot the unknown name and look it up, but I think I should probably at least add a hint, or an exercise, so that the reader knows this is the intention.

**Comment by paf31** [comment]
Fixed in the upcoming version by adding a note, thanks!
