### ISSUE TITLE
Chapter 4 - Lisp Style Formatting

### ISSUE THREAD

**Issue by ObiWahn** [paf31/purescript-book-sources#27]
Chapter 4.9 would be ideal to show this to the beginner:

``` purescript
  let pairs = (\n -> concatMap (\i -> map (\j -> [i,j])
                                          (i..n))
                               (1..n))   
```

I think this is something that does not need to be mentioned but could be shown implicit.

(I see the trouble psci vs files:)

**Comment by paf31** [comment]
Thanks, I've fixed this in the next version by using the `:paste` command.
