### ISSUE TITLE
4.4 - avoid "unsafe" and use "case of"

### ISSUE THREAD

**Issue by ObiWahn** [paf31/purescript-book-sources#29]
Unsafe immediately made me ask what the safe version looks like and how it can be used.

```
mylength :: forall a. Array a -> Int
mylength arr =
    case tail arr of
        Nothing -> 0
        Just xs -> 1+mylength(xs)
```

You need to introduce pattern matching earlier but, it would avoid open questions at that point.

**Comment by paf31** [comment]
This will be changed in the new version, and used to motivate `unsafePartial`. Thanks!
