### ISSUE TITLE
Chapter 4 - Filter vs guard

### ISSUE THREAD

**Issue by kepi** [paf31/purescript-book-sources#33]
When playing with filter and guard for `factor` function, I found out that using `filter` - `factor` function is much faster but goes out of memory fast. With `guard`, its very slow but can run for much higher numbers.

Citing the guard part:

> One further improvement we can make to the `factors` function is to move the filter inside the array comprehension.

Why this is improvement? Only because of readability of code? It will be great to further explain this as well as why filter is faster and guard can handle more so developoer can decide which is better for his current need. From text it seams like it doesn't matter and difference is only in readability.

**Comment by paf31** [comment]
I'll add a note about this in the next version, thanks!
