### ISSUE TITLE
++ No longer valid operator

### ISSUE THREAD

**Issue by Bradcomp** [paf31/purescript-book-sources#36]
As of Purescript 0.9, `++` is no longer a valid alias for `append`.  Recommend switching out to use `<>` instead.

There are a number of changes such as this that should be made to bring the book up to date with 0.9.  I respect that pull requests won't be accepted, but I would be happy to aid in making these changes as I am working through the book, in whatever way works best for you.

**Comment by paf31** [comment]
I'm planning to update the book as soon as the contrib libraries are updated. Right now, we're advising beginners to use 0.8.5 anyway, but as soon as everything is up to date, we'll start recommending 0.9.*.
