### ISSUE TITLE
Error "Unknown data constructor Int" in chapter 10 "Handling Null and Undefined Values"

### ISSUE THREAD

**Issue by shybyte** [paf31/purescript-book-sources#38]
The following code example in chapter 10:
`map runNull <$> readJSON "[1, 2, null]" :: F [Null Int]`
throws the error "**Unknown data constructor Int**"
and should be probably corrected to
`map runNull <$> readJSON "[1, 2, null]" :: F (Array (Null Int))`.

**Comment by paf31** [comment]
Thanks!
