### ISSUE TITLE
Typed holes

### ISSUE THREAD

**Issue by ghost** [paf31/purescript-book-sources#40]
Would love to see Typed holes discussed in the book. The current documentation is scarce.

Thank you in advance.

**Comment by paf31** [comment]
Yes, there are a few of these new features. I'm trying to find good places to slot them into the book, but I might end up just writing a chapter on type driven development in this case.

**Comment by kozak** [comment]
Here is a good step by step typed holes driven development gist, maybe it would be useful as inspiration: 
https://gist.github.com/NicolasT/8a79a6da9ffd8b8402cc
