### ISSUE TITLE
Chapter 6 - Exercises require knowledge from later parts of the book?

### ISSUE THREAD

**Issue by kozak** [paf31/purescript-book-sources#46]
I was trying to implement the exercises from the chapter: 
https://github.com/paf31/purescript-book-sources/blob/master/chapter6.md#functor-and-type-class-laws. 

specifically the Semigroup and Show instances for the NonEmpty type: 
`data NonEmpty a = NonEmpty a (Array a)`

I had no idea about the dependent type syntax, that is introduced in 
`6.7 Instance Dependencies` 

and struggled with the implementation. I haven't read the book from the start, so maybe that is the reason.

**Comment by paf31** [comment]
This will be fixed in the next release, thanks!
