### ISSUE TITLE
Chapter 3 - Obsolete definition of apply ($) from Prelude

### ISSUE THREAD

**Issue by noullet** [paf31/purescript-book-sources#47]
https://github.com/paf31/purescript-book-sources/blob/45f7cb81c64b2553ba7508b2dee45359bf87bcdb/chapter3.md#infix-function-application:

> `($)` is just a regular function, defined in the Prelude. It is defined as follows:
> 
> ``` purescript
> ($) :: forall a b. (a -> b) -> a -> b
> ($) f x = f x
> ```

The definition is now:

``` purescript
apply :: forall a b. (a -> b) -> a -> b
apply f x = f x
infixr 0 apply as $
```

It seems that the former definition doesn't compile anymore. It can mislead beginners into thinking that operators can be defined directly while they can now only be created as aliases.

Anyway, thanks for your work and the recent book update!

**Comment by paf31** [comment]
Fixed, thanks for the report!
