### ISSUE TITLE
Chapter 8 - Type signature of `ap`

### ISSUE THREAD

**Issue by menelaos** [paf31/purescript-book-sources#48]
The type signature of `ap` in [chapter 8](https://github.com/paf31/purescript-book-sources/blob/master/chapter8.md#monads-and-applicatives) should read

``` purescript
ap :: forall m a b. Monad m => m (a -> b) -> m a -> m b
```

instead of

``` purescript
ap :: forall m. Monad m => m (a -> b) -> m a -> m b
```

**Comment by paf31** [comment]
Fixed in the new version, thanks!
