### ISSUE TITLE
Chapter 8 - Fix `simulate` function

### ISSUE THREAD

**Issue by menelaos** [paf31/purescript-book-sources#49]
The `simulate` function in [chapter 8](https://leanpub.com/purescript/read#leanpub-auto-mutable-state) needs to be corrected. Currently it reads:

``` purescript
simulate :: forall eff h. Number -> Number -> Number -> Eff (st :: ST h | eff) Number
simulate x0 v0 time = do
  ref <- newSTRef { x: x0, v: v0 }
  forE 0.0 (time * 1000.0) $ \i -> do
    modifySTRef ref \o ->
      { v: o.v - 9.81 * 0.001
      , x: o.x + o.v * 0.001
      }
    pure unit
  final <- readSTRef ref
  return final.x
```
- Use `pure` instead of `return`
- `forE` takes `Int` arguments
- Stylistic issue: `\i -> do` could be replaced with `\_ -> do`

**Comment by paf31** [comment]
Fixed in the new version, thanks!
