### ISSUE TITLE
Rewrite `factors` to use the `any` function?

### ISSUE THREAD

**Issue by Javran** [paf31/purescript-book-sources#5]
This is more like a question than an issue.

From chapter 4, one exercise wants us to rewrite `factors` using `any` function.
But it makes more sense to me rewriting `isPrime` using `any` function.
Since `any` can only return a Bool value, the information is IMHO just not enough to construct the resulting list of `factors`.

**Comment by paf31** [comment]
This exercise is removed in the new version.
