### ISSUE TITLE
Chapter 11 - Typo in code in 11.15

### ISSUE THREAD

**Issue by menelaos** [paf31/purescript-book-sources#50]
In chapter [11.15](https://leanpub.com/purescript/read#leanpub-auto-implementing-game-logic), there is a small typo in the following line:

``` purescript
tell (L.singleton "You now have the " <> show item)
```

It should read something like this:

``` purescript
tell $ L.singleton ("You now have the " <> show item)
```

**Comment by paf31** [comment]
Thanks! I'll fix this in the upcoming release.
